### ISSUE TITLE
Could you help maintain the website "www.slumbot.com"

### ISSUE THREAD

**Issue by rpSebastian** [ericgjackson/slumbot2019#16] opened 2020-10-30 04:23 UTC
Dear @ericgjackson

I developed a poker agent recently and want to compare it with slumbot which is the only public agent on the Internet. Unfortunately, the website crashed this morning and the error message is "Server error: couldn't save session". Could you help maintain the website "www.slumbot.com"?

Thank you very much! O(∩_∩)O

**Comment by rpSebastian** [comment] 2020-10-31 01:46
Thanks very much for your help.

**Comment by jidma** [comment] 2021-01-13 01:56
the problem is back again

**Comment by ericgjackson** [comment] 2021-01-13 02:32
Should be fixed now.

**Comment by rpSebastian** [comment] 2021-12-11 03:32
Hi, @ericgjackson. There are some problems with the website again. Can you help to maintain it? Thank you very much!  O(∩_∩)O

**Comment by ericgjackson** [comment] 2021-12-11 04:30
Should be fixed now.

**Closed by ericgjackson** 2021-12-11 04:30 UTC
